name: Pull Request Check

on:
  pull_request:
    branches:
      - main
      - 'release/**'
  push:
    branches:
      - main
      - 'release/**'
      
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build project
      run: MSBuild.exe HunterPie.Native.vcxproj /p:Configuration=Release /p:Platform=x64 /v:n

    - name: Run unit tests
      run: dotnet test *.Tests

    - name: Run formatter
      run: dotnet format --verify-no-changes
